### PR TITLE
Add Wednesday remaining Talks

### PR DESCRIPTION
**Pull request by UsamaKarim**
- Added remaining talks for Wednesday (05 July)
- Reorganized some talks

### CODE REVIEW

**Comment by UsamaKarim** [comment]
The length of the text of one talk was quite lengthy, That's why I have added some space to every talk to keep the structure intact.

**Review by bizz84 — APPROVED** [review]

**Comment by bizz84** [comment]
@UsamaKarim this is great, thank you!

**Comment by bizz84** [comment]
@UsamaKarim FYI, someone else also volunteered to do the work and he's already at work on the Thursday and Friday talks. So maybe hold on before doing more work.

**Comment by UsamaKarim** [comment]
@bizz84 Awesome.

**Pull request merged**
